version: 2.1
jobs:
  build:
    machine: true
     
    steps:
      - checkout
      - run:
          name: Start the PostgreSQL container
          command: |
            set -x
            docker run --name pactbroker-db -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_USER=some-postgres -d postgres

      - run:
          name: Connect to the container and execute psql
          command: |
            set -x
            docker run --name pactbroker --link pactbroker-db:postgres -e PACT_BROKER_DATABASE_USERNAME=pactbrokeruser -e PACT_BROKER_DATABASE_PASSWORD=TheUserPassword -e PACT_BROKER_DATABASE_HOST=postgres -e PACT_BROKER_DATABASE_NAME=pactbroker -d -p 80:80 dius/pact-broker

      - run:
          name: Run the following SQL configuration scripts
          command: |
            echo "CREATE USER pactbrokeruser WITH PASSWORD 'TheUserPasswordNew';" 
            echo "CREATE DATABASE pactbroker WITH OWNER pactbrokerusernew;"
            echo "GRANT ALL PRIVILEGES ON DATABASE pactbroker TO pactbrokerusernew;"

      - run:
          name: Start the PactBroker container
          command: |
            set -x
            docker run --name pactbroker_ci --link pactbroker-db:postgres -e PACT_BROKER_DATABASE_USERNAME=pactbrokeruser -e PACT_BROKER_DATABASE_PASSWORD=TheUserPassword -e PACT_BROKER_DATABASE_HOST=postgres -e PACT_BROKER_DATABASE_NAME=pactbroker -d -p 23:23 dius/pact-broker

      - run: 
          name: Install project dependencies
          command: npm install -f
      - run:
          name: Run consumer contract tests
          command: npm run test:pact:consumer
      - run:
          name: Publish contract to Pactflow
          command: npm run publish:pact
      - run:
          name: Run provider contract tests
          command: npm run test:pact:provider
      - run:
          name: Tag latest provider version
          command: npm run create:provider:tag
      - run:
          name: Can I deploy consumer?
          command: npm run can:i:deploy:consumer
      - run:
          name: Tag latest consumer version
          command: npm run create:consumer:tag
